# Generated by Django 2.2.4 on 2019-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20190929_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.AddField(
            model_name='homework',
            name='questions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lecture',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
