# Generated by Django 2.2.4 on 2019-10-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
