# Generated by Django 2.2.4 on 2019-10-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_homework_question_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='question_img',
            field=models.ImageField(blank='True', null='True', upload_to='homeworks'),
        ),
    ]
