# Generated by Django 2.2.4 on 2019-10-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_number', models.TextField()),
                ('recording', models.FileField(upload_to='sidebyside1')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidebyside1.Chapter')),
            ],
        ),
    ]
